version: 2
jobs:
  build:
    docker:
      - image: cimg/php:8.2.4
      - image: mysql:5.7.39
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: root
      MYSQL_PASSWORD: 
      MYSQL_DATABASE: freya
    steps:
      - checkout
      - run:
          name: Install PHP Extensions
          command: |
            sudo apt update
            sudo apt install -y zlib1g-dev libsqlite3-dev
            sudo docker-php-ext-install zip
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "composer.json" }}
            - v1-dependencies-
      - run:
          name: "Install Dependencies"
          command: composer install -n --prefer-dist
      - save_cache:
          key: v1-dependencies-{{ checksum "composer.json" }}
          paths:
            - ./vendor
      - run:
          name: "Run tests"
          command: composer test
