home:
    path: /home
    controller: App\Controller\HomeController::index
    methods: GET
    
app_logout:
    path: /logout
    

controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute



